### ISSUE TITLE
Check README.md

### ISSUE THREAD

**Issue by vvasuki** [sanskrit/sanscript.js#19]
Is following bit still ok? Will everything work if you open a file://... rather than a http location?

```
<script src="node_modules/@sanskrit-coders/sanscript/sanscript.js"></script>
var output = Sanscript.t(input, from, to, options);
```

**Comment by psvenk** [comment]
This should still work because `dist.js` reads from `src/sanscript.js` and writes to `sanscript.js` in the root of the repository, so running `npm run dist` before running `npm publish` should put the generated file in the same path where the source file used to be.

**Comment by vvasuki** [comment]
Ok, thanks!
