### ISSUE TITLE
Set up CI/CD

### ISSUE THREAD

**Issue by rramphal** [sanskrit/sanscript.js#21]
As mentioned in https://github.com/sanskrit/sanscript.js/pull/13#issuecomment-668911477.

We will eventually have `npm run lint`, `npm run test`, `npm run validate`, and `npm run dist` — all of which are good build steps.

**Comment by vvasuki** [comment]
Great idea. I suggest setting up github actions - that way pull requests are automatically tested. Will you do it @rramphal ?

**Comment by rramphal** [comment]
@vvasuki Working on it now.
